### ISSUE TITLE
toHaveBeenCalledOnceWith only asserts a match on the first parameter.

### ISSUE THREAD

**Issue by GRollason** [jest-community/jest-extended#517] opened 2022-10-12 17:59 UTC
I'm not sure if this would be classed as a bug or a feature, so apologies for any mistakes raising the issue.

**Feature Request**

Description: toHaveBeenCalledOnceWith currently only matches against the first parameter provided to a mock function.

Possible solution:
In `toHaveBeenCalledOnceWith.js`, line 40 reads
`const pass = passOnce && this.equals(expected, received.mock.calls[0][0]);`
I believe that this should probably be changed to `this.equals(expected, received.mock.calls[0]);` and assert equality on the whole array of parameters passed to the mock function in the first call. This may need the function declaration to be changed to `toHaveBeenCalledOnceWith(received, ...expected)` or similar to handle multiple arguments.

If this is desired, or not so simple to implement, it would be good to make this clear in the documentation.

**Comment by vandor** [comment] 2022-10-22 21:13
I'm seeing the same behavior, and it's really unexpected to me. The `toHaveBeenCalledOnceWith` matcher is named to suggest it's a combination of `toHaveBeenCalledTimes(1)` and `toHaveBeenCalledWith`. What's the intended behavior?

**Comment by loyaj** [comment] 2022-10-22 23:51
I'm seeing the same behavior, and it's really unexpected to me. The `toHaveBeenCalledOnceWith` matcher is named to suggest it's a combination of `toHaveBeenCalledTimes(1)` and `toHaveBeenCalledWith`. What's the intended behavior?

**Comment by keeganwitt** [comment] 2022-10-25 03:12
@loyaj What you are suggesting is implied by the name is the intended behavior.

**Comment by keeganwitt** [comment] 2022-10-25 03:27
I'm going to close this one in favor of #518, just because that one more precisely describes the issue.

**Comment by loyaj** [comment] 2022-10-25 04:37
Oh, I’m still thinking this issue is describing a separate problem from #518, is it not? Jest’s `toHaveBeenCalledOnceWith` matches on all arguments, not just the first one.

**Comment by keeganwitt** [comment] 2022-10-25 04:46
Ah. You're right. I was looking at was ultimately implemented, by that doesn't match what was described in #138.

**Comment by keeganwitt** [comment] 2022-11-08 15:09
I haven't found a way to make this work with varargs. Jest seems to pass only the first parameter as `expected` into the matcher.

**Comment by Maxim-Mazurok** [comment] 2023-01-31 00:27
That's a pretty big issue... We were about to introduce `jest-extended` to our project just because of this matcher, good thing that types [didn't work](https://github.com/jest-community/jest-extended/issues/518#issuecomment-1409561640) :)
Would be great to see this fixed or removed if it can't be fixed, I imagine lots of people have flawed tests because of this misunderstanding.

**Closed** 2023-02-02 16:25 UTC
